spring.application.name=School Management
spring.datasource.url=jdbc:postgresql://localhost:5432/school_management_db
spring.datasource.username=postgres
spring.datasource.password=@Tumie8Ntsilo

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
